# Generated by Django 4.2 on 2024-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/images", verbose_name="Image"
            ),
        ),
    ]
