# Generated by Django 4.2 on 2024-07-14 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeBatchArchived",
            fields=[],
            options={
                "verbose_name": "Code Archive",
                "verbose_name_plural": "Code Archive",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cards.codebatch",),
        ),
    ]
