# Generated by Django 4.2 on 2024-07-02 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="automatically generated",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Purchasing Code",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="automatically generated",
                        max_length=120,
                        null=True,
                        verbose_name="Password",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "extra_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="product_codes",
                        to="services.product",
                        verbose_name="Extra Products",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_codes",
                        to="services.productgroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchasing Code",
                "verbose_name_plural": "Purchasing Codes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NFCCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_cards",
                        to="cards.purchasingcode",
                        verbose_name="Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "NFC Card",
                "verbose_name_plural": "NFC Cards",
                "ordering": ("-created_at",),
            },
        ),
    ]
