# Generated by Django 4.2 on 2024-07-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("archive", "__first__"),
        ("settings", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NFCCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default="", editable=False, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_urls",
                        to="archive.urlbatch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "NFC Card",
                "verbose_name_plural": "NFC Cards",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PurchasingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="automatically generated",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Purchasing Code",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="automatically generated",
                        max_length=120,
                        null=True,
                        verbose_name="Password",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product1", "Product 1"),
                            ("product2", "Product 2"),
                            ("product3", "Product 3"),
                            ("product4", "Product 4"),
                        ],
                        max_length=500,
                        null=True,
                        verbose_name="Product",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_codes",
                        to="archive.codebatch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_code",
                        to="cards.nfccard",
                        verbose_name="Card",
                    ),
                ),
                (
                    "duration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="settings.linkduration",
                        verbose_name="Duration",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_codes",
                        to="settings.productgroup",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchasing Code",
                "verbose_name_plural": "Purchasing Codes",
                "ordering": ("-created_at",),
            },
        ),
    ]
