# Generated by Django 4.2 on 2024-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebatch",
            name="count",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Quantity"
            ),
        ),
    ]
